# Generated by Django 5.2.5 on 2025-08-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_delivery_app", "0002_userbillinginfo_task_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="health_delivery_app.team",
            ),
        ),
    ]
