# Generated by Django 5.2.5 on 2025-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_delivery_app", "0003_project_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
